### PR TITLE
Change license to (Apache-2.0 WITH LLVM-exception) OR Apache-2.0 OR MIT

### LINKED ISSUE #9: License
Is there a reason this isn't dual-licensed with Apache 2.0 OR MIT ?

### PR DESCRIPTION
**Pull request by sunfishcode**
See discussion in #9.

Fixes #9.

### CODE REVIEW

**Comment by mati865** [comment]
Hey @sunfishcode.

Hate to ask on ETA but https://github.com/rust-lang/rust/pull/63806 is waiting on relicensed version of `wasi` or adding `wasi` to the exception list.

If you want more time it's fine, just let me know so I'll split `libc` update from that PR (to fix bug).

**Comment by mati865** [comment]
Thank you for merging it. Do you mind publishing new release on crates.io?

**Comment by sunfishcode** [comment]
`cargo publish` is failing, with this message:
```
error: api errors (status 200 OK): unknown license or other term: (Apache-2.0; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
```
At first glance, this looks like a bug in cargo, because "Apache-2.0" is a valid license identifier. Anyone have any ideas?

**Comment by mati865** [comment]
No idea, maybe it doesn't like `(` before license, I'll check the code soon.

**Comment by sunfishcode** [comment]
Looks like it indeed doesn't like `(`: https://github.com/rust-lang-nursery/license-exprs/issues/3. But it also looks like [`WITH` has a higher precedence than `OR`](https://spdx.org/spdx-specification-21-web-version), so I'll try removing the parens.

**Comment by sunfishcode** [comment]
That worked! 0.6.0 is up, with the new license.

**Pull request merged**
